version: '3'
services:
  wordpress:
    build: ./
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data
      - ./wp-content:/app/wp-content/
      # - ./dev-theme:/app/wp-content/themes/dev-theme
      # - ./dev-plugin:/app/wp-content/plugins/dev-plugin
      - ./local-scripts:/local-scripts/

    environment:
      DB_NAME: wordpress
      DB_PASS: root
      DEV_THEME_USERNAME: holger1411
      DEV_THEME_REPONAME: understrap
      PLUGINS: >-
        academic-bloggers-toolkit,
        co-authors-plus,
        [WP-API]https://github.com/WP-API/WP-API/archive/master.zip,
  db:
    image: mariadb:10 # or mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 22222:80
volumes:
  data:
